---
kafka:
  clientId: convergency
  topic: maxwell
  groupId: main
  brokers:
  - kafka-ufo.service.upyun:9092

adapters:
  - host: 192.168.5.30:3306
    database: robin
    table: log_import_fails
    endpoint:
      driver: es6
      key: id
      index: robin_log_import_fails
      type: robin_log_import_fails
      host: es-zico2.service.upyun:9500